name: 'Fix Style'
on:
  issue_comment:
    types: [created]
  pull_request_target:

jobs:
  fix-style:
    if: |
      github.repository_owner == 'bdice' &&
      (
        github.event_name == 'pull_request_target' ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/fix style')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python -m pip install pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure --color=always
      #- uses: EndBug/add-and-commit@v9
      #  # Only commit changes if triggered by a comment starting with '/fix style'
      #  if: |
      #    failure() &&
      #    github.event_name == 'issue_comment' &&
      #    github.event.issue.pull_request &&
      #    startsWith(github.event.comment.body, '/fix style')
      #  with:
      #    fetch: false
      #    message: 'Fix style.'
